---
- name: Prepare Proxmox template with Cloud-Init
  hosts: all
  become: false
  vars_files:
    - vars/main.yaml
    - vars/secrets.yaml

  tasks:
    - name: Hash user password
      ansible.builtin.set_fact:
        encrypted_password: "{{ cipassword | password_hash('sha512') }}"

    - name: Get cloud image
      ansible.builtin.get_url:
        url: "{{ cloud_image.url }}"
        dest: "{{ cloud_image.storage }}/{{ cloud_image.name }}"
        owner: root
        group: root
        mode: '0644'
        timeout: 60

    - name: Check VM exists
      ansible.builtin.shell: "qm status {{ vm.id }}"
      register: vm_status
      ignore_errors: true
      args:
        executable: /bin/bash
      changed_when: vm_status.rc == 0 or vm_status.rc == 1

    - name: Create base VM
      ansible.builtin.shell: "qm create {{ vm.id }} --name {{ template.name }} --core {{ vm.cores }} --memory {{ vm.memory }} --net0 virtio,bridge=vmbr0 --cpu {{ vm.cpu }}"
      args:
        executable: /bin/bash
      when: vm_status.rc != 0
      register: create_vm
      changed_when: create_vm.rc == 0
      failed_when: create_vm.rc not in [0]

    - name: Import disk
      ansible.builtin.shell: |
        qm importdisk {{ vm.id }} {{ cloud_image.storage }}/{{ cloud_image.name }} {{ proxmox.storage }}
      args:
        executable: /bin/bash
      when: vm_status.rc != 0
      register: import_disk
      changed_when: import_disk.rc == 0
      failed_when: import_disk.rc not in [0]

    - name: Attach disk
      ansible.builtin.shell: |
        qm set {{ vm.id }} --scsihw virtio-scsi-single --scsi0 {{ proxmox.storage }}:vm-{{ vm.id }}-disk-0
      args:
        executable: /bin/bash
      when: vm_status.rc != 0
      register: attach_disk
      changed_when: attach_disk.rc == 0
      failed_when: attach_disk.rc not in [0]

    - name: Setup Cloud-Init
      ansible.builtin.shell: |
        qm set {{ vm.id }} --ide2 {{ proxmox.storage }}:cloudinit --boot c --bootdisk scsi0 --serial0 socket --vga serial0 --citype nocloud --ipconfig0 ip=dhcp
      args:
        executable: /bin/bash
      when: vm_status.rc != 0
      register: cloud_init
      changed_when: cloud_init.rc == 0
      failed_when: cloud_init.rc not in [0]

    - name: Add SSH key
      ansible.builtin.copy:
        dest: "{{ user_data.storage_path }}/{{ vm.id }}.pub"
        content: "{{ sshkey }}"
        remote_src: false
        owner: root
        group: root
        mode: '0644'
      when: vm_status.rc != 0

    - name: Cleanup SSH key
      ansible.builtin.file:
        path: "{{ user_data.storage_path }}/{{ vm.id }}.pub"
        state: absent
      when: vm_status.rc != 0

    - name: Enable QEMU
      ansible.builtin.shell: |
        qm set {{ vm.id }} --agent 1
      args:
        executable: /bin/bash
      when: vm_status.rc != 0 and vm.QEMU_AGENT
      register: enable_qemu_agent
      changed_when: enable_qemu_agent.rc == 0
      failed_when: enable_qemu_agent.rc not in [0]

    - name: Expand disk
      ansible.builtin.shell: |
        qm resize {{ vm.id }} scsi0 {{ vm.resize_disk }}G
      args:
        executable: /bin/bash
      when: vm_status.rc != 0
      register: resize_disk
      changed_when: resize_disk.rc == 0
      failed_when: resize_disk.rc not in [0]

    - name: Add user-data
      ansible.builtin.template:
        src: "./templates/{{ user_data.file }}"
        remote_src: false
        dest: "{{ user_data.storage_path }}/{{ vm.id }}-user-data.yaml"
        owner: root
        group: root
        mode: '0644'
      when: vm_status.rc != 0

    - name: Link user-data
      ansible.builtin.shell: |
        qm set {{ vm.id }} --cicustom "user={{ user_data.storage }}:snippets/{{ vm.id }}-user-data.yaml"
      args:
        executable: /bin/bash
      when: vm_status.rc != 0
      register: attach_user_data
      changed_when: attach_user_data.rc == 0
      failed_when: attach_user_data.rc not in [0]

    - name: Setup UEFI
      ansible.builtin.shell: |
        qm set {{ vm.id }} --bios ovmf --machine q35 --efidisk0 {{ proxmox.storage }}:0
      args:
        executable: /bin/bash
      when: vm_status.rc != 0 and vm.UEFI
      register: enable_uefi
      changed_when: enable_uefi.rc == 0
      failed_when: enable_uefi.rc not in [0]

    - name: Create template
      ansible.builtin.shell: |
        qm template {{ vm.id }}
      args:
        executable: /bin/bash
      when: vm_status.rc != 0
      register: convert_template
      changed_when: convert_template.rc == 0
      failed_when: convert_template.rc not in [0]
